services:
  - type: web
    name: bank-jdc-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bank-jdc-db
          property: connectionString

databases:
  - name: bank-jdc-db
    databaseName: bank_jdc
    plan: free
